version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: dgz
      POSTGRES_PASSWORD: dgzpass
      POSTGRES_DB: cadastre_db
    volumes:
      - ./backend/postgres/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  api:
    build: ./backend/fastapi
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dgz:dgzpass@db:5432/cadastre_db
    volumes:
      - ./backend/fastapi:/app:rw
    ports:
      - "8000:8000"

  web:
    image: nginx:stable-alpine
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
